CREATE TABLE posts
(
  author VARCHAR(20) NOT NULL,
  title VARCHAR(140) DEFAULT '' NOT NULL,
  body LONGTEXT NOT NULL,
  date DATE NOT NULL,
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
