package ccampo133.blog.repository;

import ccampo133.blog.domain.Post;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;

// More Spring Data JPA magic... the CRUD and pagination queries are all generated by
// the methods in the PagingAndSortingRepository interface. Talk about abstraction...

@Repository
public interface PostRepository extends PagingAndSortingRepository<Post, Long> {
}
